#!/usr/bin/env python
"""Serve the real dashboard/index.html against the real src/api/handler.py, both talking to the
in-memory World - a full local stand-in for API Gateway + Lambda + DynamoDB, stdlib only.

    python local_demo/server.py           # http://localhost:8787

Open that URL, click "Ask the agent", or drive scenarios from another terminal with
run_demo.py - the dashboard updates on its own 10-second poll (dashboard/index.html:auto-refresh).
"""

import json
import sys
import webbrowser
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlparse

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from local_demo import bootstrap  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
DASHBOARD_DIR = REPO_ROOT / "dashboard"
PORT = 8787

from local_demo.scenarios import ASG_NAME, DEV_INSTANCE, PROD_INSTANCE  # noqa: E402

CONFIG_JS = (
    "// Generated by local_demo/server.py for the offline demo - the real deploy.sh writes this\n"
    "// from the CloudFormation stack outputs instead.\n"
    f'window.LEASH_CONFIG = {{ apiUrl: "http://localhost:{PORT}", '
    f'devInstanceId: "{DEV_INSTANCE}", prodInstanceId: "{PROD_INSTANCE}", asgName: "{ASG_NAME}" }};\n'
)


def _api_event(method: str, path: str, query: dict, body: bytes | None) -> dict:
    """Build the HTTP API v2 event shape api.handler.handler() expects."""
    return {
        "routeKey": f"{method} {path}",
        "rawPath": path,
        "queryStringParameters": {k: v[0] for k, v in query.items()} or None,
        "body": body.decode("utf-8") if body else None,
        "isBase64Encoded": False,
    }


class Handler(BaseHTTPRequestHandler):
    def log_message(self, fmt, *args):  # quieter default logging
        print("  [server] " + (fmt % args))

    def _send_static(self, path: Path, content_type: str):
        try:
            data = path.read_bytes()
        except FileNotFoundError:
            self.send_response(404)
            self.end_headers()
            return
        self.send_response(200)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def _send_api(self, event: dict):
        from api.handler import handler as api_handler

        resp = api_handler(event, None)
        body = (resp.get("body") or "").encode("utf-8")
        self.send_response(resp.get("statusCode", 200))
        for k, v in (resp.get("headers") or {}).items():
            self.send_header(k, v)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_OPTIONS(self):
        self._send_api({"routeKey": "OPTIONS /", "body": None})

    def do_GET(self):
        parsed = urlparse(self.path)
        if parsed.path == "/" or parsed.path == "/index.html":
            self._send_static(DASHBOARD_DIR / "index.html", "text/html; charset=utf-8")
        elif parsed.path == "/config.js":
            self.send_response(200)
            self.send_header("Content-Type", "application/javascript")
            data = CONFIG_JS.encode("utf-8")
            self.send_header("Content-Length", str(len(data)))
            self.end_headers()
            self.wfile.write(data)
        elif parsed.path in ("/health", "/audit", "/policies"):
            query = parse_qs(parsed.query)
            self._send_api(_api_event("GET", parsed.path, query, None))
        else:
            self.send_response(404)
            self.end_headers()

    def do_POST(self):
        parsed = urlparse(self.path)
        length = int(self.headers.get("Content-Length", 0) or 0)
        body = self.rfile.read(length) if length else b""
        if parsed.path == "/ask":
            self._send_api(_api_event("POST", parsed.path, {}, body))
        else:
            self.send_response(404)
            self.end_headers()


def main():
    ready, msg = bootstrap.ollama_ready()
    print(("[ok] " if ready else "[!!] ") + msg)
    bootstrap.setup(reset_world=True)

    httpd = ThreadingHTTPServer(("localhost", PORT), Handler)
    url = f"http://localhost:{PORT}"
    print(f"\nLeash local dashboard: {url}")
    print("Drive scenarios from another terminal:  python local_demo/run_demo.py disk-full")
    print("Or use the 'Ask the agent' box on the page for the chat-based denial scenarios.")
    print("Ctrl+C to stop.\n")
    try:
        webbrowser.open(url)
    except Exception:
        pass
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
